name: seashell-app
region: blr
services:
- dockerfile_path: server2/Dockerfile
  github:
    branch: feature-server-host-server
    deploy_on_push: true
    repo: COS301-SE-2022/CryptoHub
  http_port: 80
  instance_count: 1
  instance_size_slug: basic-xs
  name: cryptohub-server-2
  routes:
  - path: /
  source_dir: server2/