name: .NET

on:
  pull_request:
    branches: ["develop"]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  build:
    runs-on: ubuntu-latest
    environment: de

    steps:
      # - uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 0
      # - name: Set up JDK 11
      #   uses: actions/setup-java@v1
      #   with:
      #     java-version: 11
      # - name: Cache SonarCloud packages
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.sonar/cache
      #     key: ${{ runner.os }}-sonar
      #     restore-keys: ${{ runner.os }}-sonar
      # - name: Cache Maven packages
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.m2
      #     key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      #     restore-keys: ${{ runner.os }}-m2
      # - name: Build and analyze
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   run: mvn -f server/pom.xml "-B" verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar "-Dsonar.projectKey=COS301-SE-2022_CryptoHub"
      - uses: actions/checkout@v3
      - name: Envs
        run: |
          echo ${{ secrets }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: |
          cd server2
          dotnet restore
      - name: Build
        run: |
          cd server2
          dotnet build --no-restore
      - name: Test
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
        run: |
          cd server2
          dotnet test --no-build --verbosity normal

on:
  push:
    branches: ["develop"]

jobs:
  build_docker:
    name: Build Docker image and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push API
        uses: docker/build-push-action@v3
        with:
          context: "${{ github.server_url }}/${{ github.repository }}.git#${{ github.ref }}:server2"
          push: true
          tags: codeforce301/cryptohubapi:latest
      - name: Build and Push Client
        uses: docker/build-push-action@v3
        with:
          context: "${{ github.server_url }}/${{ github.repository }}.git#${{ github.ref }}:client"
          push: true
          tags: codeforce301/cryptohubclient:latest
      - name: Build and Push AI
        uses: docker/build-push-action@v3
        with:
          context: "${{ github.server_url }}/${{ github.repository }}.git#${{ github.ref }}:AI/App"
          push: true
          tags: codeforce301/cryptohubai:latest
  update_on_linode:
    name: Update image on Linode
    needs: "build_docker"
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password for system
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: bash update.sh
