name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: actions/checkout@v3
    - name: Envs
      run: |
        echo ${{ secrets }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: |
        cd server2
        dotnet restore
    - name: Build
      run: |
        cd server2
        dotnet build --no-restore
    - name: Test
      env :
        DOPPLER_TOKEN : echo ${{ secrets.DOPPLER_TOKEN }}
      run: |
        cd server2
        dotnet test --no-build --verbosity normal
